### PR TITLE
Add standard Python .gitignore entries

### PR DESCRIPTION
**Pull request by jonafato**
Additionally, remove files that should have been ignored by the updates
here.

### CODE REVIEW

**Comment by jonafato** [comment]
@th3r00t It looks like there are also some `.ipynb` and `.json` files as well as some editor configuration that you may want to include in the ignore file as well. I'm happy to update my PR here to include those if you'd like.

**Comment by th3r00t** [comment]
Yah its been on my todo list for a while now tbh, if you want to go ahead and add those in that would be great!

**Comment by jonafato** [comment]
Updated! Please review and let me know if I've missed or added anything I should not have.

**Comment by th3r00t** [comment]
Looks good, thanks for that!

**Pull request merged**
